### ISSUE TITLE
Make metadata optional

### ISSUE THREAD

**Issue by feltnerm** [imhoffd/node-jsondir#3]
I'd love to have the metadata (content, path, permissions, etc) that dir2json generates be optional.

I'd argue that metadata should not be included in the result unless the user specifics explicitly that they want it. Even then, maybe they could choose which metadatas they'd like to have in the result. This would speed up computation as well. Again, I have an idea to contribute a patch, but it depends on time.

**Comment by imhoffd** [comment]
Good idea. Right now you can disable the reading of file content, but this should be generalized to all attributes. It should be an `attributes` option that is an array of attribute names you want to include (default being empty array.. so no attributes).

Unfortunately some I/O needs to happen (specifically getStats) and simply not requesting the associated attributes will not speed things up significantly.

There also needs to be more attributes included. I only see `path`, `type`, and `content`. The rest of the attributes should be available for inclusion.

**Comment by imhoffd** [comment]
Done
